# Site settings
title: "Karollyn Larissa de Quadros"
description: "Environmental Engineer | Hydrology & Remote Sensing Researcher"
author: "Karollyn Larissa de Quadros"
email: "karollynq.ambiental@gmail.com"

# Social media links
github_username: karollynquadros
linkedin_username: karollyn-larissa-de-quadros
twitter_username: karollynquadros

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  - publications
  - news
