# Site settings
title: "Karollyn Larissa de Quadros"
description: "Engenheira Ambiental - Mestranda"
author: "Karollyn Larissa de Quadros"
email: "karollynq.ambiental@gmail.com"

# Social media links
github_username: karollynquadros
linkedin_username: karollyn_quadros

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  - publications
  - news
  - showcase
